### ISSUE TITLE
Blade директива кэшируется вместе с данными

### ISSUE THREAD

**Issue by DmitriyRuppel** [avto-dev/back2front-laravel#2]
## Describe the bug

При первом вызове blade директивы @back_to_front_data в кэш попадает результат работы в месте с данными, которые были установлены. 

### Expected behaviour

При каждом вызове должны выводится актуальные данные установленные в стек.

### Actual behaviour

При вызове директивы на другой странице выводятся данные, которые были установлены в стек перед первым вызовом директивы.

### Steps to reproduce the behavior:

Установить данные
```
<?php
backToFrontStack()->put('test', 'some_value');
```

Вывести на странице JS, устанавливающий объект с дынными при помощи blade директивы

```@back_to_front_data```

Установить другие данные
```
<?php
backToFrontStack()->put('test', 'some_value2);
```

Снова вывести на страницу blade директивой 

```@back_to_front_data```

Данные останутся старыми.

## System information

 - PHP version: 7.2
 - Laravel framework: 5.6.34
 - Package version: 1.0.2

**Comment by tarampampam** [comment]
@DmitriyRuppel can you update your previously created [PR]?

[PR]:https://github.com/avto-dev/back2front-laravel/pull/1
